{{.Values}}
#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ .Values.metadata.name }}
#  namespace: {{ .Values.metadata.namespace }}
#spec:
#  type: {{ .Values.spec.type }}
#  ports:
#    - port: {{ .Values.service.port }}
#      targetPort: http
#      protocol: TCP
#      name: http
#  selector:
#    {{- include "dipservice.selectorLabels" . | nindent 4 }}
