#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ include "dip.fullname" . }}
#  labels:
#    {{- include "dip.labels" . | nindent 4 }}
#spec:
#  type: {{ .Values.service.type }}
#  ports:
#    - port: {{ .Values.service.port }}
#      targetPort: http
#      protocol: TCP
#      name: http
#  selector:
#    {{- include "dip.selectorLabels" . | nindent 4 }}
{{ include "test.service" . }}